### ISSUE TITLE
Does it work on win2008 r2 ?  

### ISSUE THREAD

**Issue by kevinkelin** [DoogeJ/SmartHDD#3]
Hello, I run this program in windows 2008 r2 and it shows "An error occurred while querying for WMI data: Not supported" 
I use python code run you code 
``` python 
import wmi
smartHddinfo = wmi.WMI(moniker="//./root/wmi").query("Select * from MSStorageDriver_FailurePredictData")
```
and shows 
> pywintypes.com_error: (-2147217396, 'OLE error 0x8004100c', None, None) 

and I checked '8004100c' means `Specified class is not valid.` 
Does this mean this function not supported in windows 2008 r2 ?

**Comment by NoxiousPluK** [comment]
I honestly have no idea!

0x8004100c is WBEM_E_NOT_SUPPORTED so it is likely either not possible to do this.

But, check from line 255: https://github.com/DoogeJ/SmartHDD/blob/master/SmartHDD/Program.cs#L255

Because the ManagementObjectSearcher first does a `"Select * from Win32_DiskDrive"` which I do not see in your example. This might be a requiremend.

(Original code there is by Llewellyn Kruger from http://www.know24.net/blog/C+WMI+HDD+SMART+Information.aspx)

**Comment by NoxiousPluK** [comment]
@kevinkelin Also see this:
https://social.technet.microsoft.com/Forums/lync/en-US/9c0156fa-7b60-4698-99a8-c2828125ffec/wmi-query-to-msstoragedriver-and-child-classes-ie-msstoragedriverfailurepredictdata-generates?forum=winserverManagement
